apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    app: frontend
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: fr
          image: telerepo.azurecr.io/integration-fr:v3
          command: ["dotnet", "Frontend.dll"]
          args: ["9100"]
          ports:
          - containerPort: 9100
          resources:
            requests:
              cpu: "1" 
          env:
          - name: TELEPATHY_SESSION_HOST
            value: http://session:5001
          - name: TELEPATHY_NSQ_HOST
            value: "nsqd:4150"
          - name: TELEPATHY_REDIS_HOST
            value: v2test.redis.cache.windows.net:6380,password=PNfbW2RD4s9NL6b7VZN7lxoeRScNJsI1XIbTrDeN7Bs=,ssl=True,abortConnect=False
            
    

          
