apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    app: frontend
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: fr
          image: telerepo.azurecr.io/integration-fr:v3
          command: ["dotnet", "Frontend.dll"]
          args: ["9100"]
          ports:
          - containerPort: 9100
          resources:
            requests:
              cpu: "1" 
          env:
          - name: TELEPATHY_SESSION_HOST
            value: http://session:5001

          - name: TELEPATHY_NSQ_HOST
            value: "nsqd:4150"

          - name: REDIS_CACHE_NAME
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: redisCacheName

          - name: TELEPATHY_REDIS_HOST
            value: ($REDIS_CACHE_NAME).redis.cache.windows.net:6380,password=($REDIS_CACHE_ACCESS_KEY),ssl=True,abortConnect=False
            
    

          
