trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'fdcc5225-3a32-4448-bfb1-61a524dbe2a1'
  containerRegistry: 'telerepo.azurecr.io'
  dispatcherDockerfile: 'dispatcher/Dockerfile'
  sessionDockerfile: 'Dockerfile.session'
  frontendDockerfile: 'Dockerfile.frontend'
  resourceGroup: 'haiguoteletest'
  aksClusterName: 'telepathyakscluster'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:

- stage: Build
  displayName: Build stage
  jobs:
  - job: buildDispatcher
    displayName: Build dispatcher image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push dispatcher image to ACR
      inputs:
        command: buildAndPush
        repository: telepathydispatcher
        dockerfile: $(dispatcherDockerfile)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest
  
  - job: buildSession
    displayName: Build session image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push session image to ACR
      inputs:
        command: buildAndPush
        repository: telepathysession
        dockerfile: $(sessionDockerfile)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

  - job: buildFrontend
    displayName: Build frontend image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push frontend image to ACR
      inputs:
        command: buildAndPush
        repository: telepathyfrontend
        dockerfile: $(frontendDockerfile)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - job: ARMDeployment
    displayName: Deploy ARM resources
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'Subscription-1(a486e243-747b-42de-8c4c-379f8295a746)'
          KeyVaultName: 'haiguopipelinevault'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Subscription-1(a486e243-747b-42de-8c4c-379f8295a746)'
          subscriptionId: 'a486e243-747b-42de-8c4c-379f8295a746'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroup)'
          location: 'East US'
          templateLocation: 'URL of the file'
          csmFileLink: 'https://github.com/HyphonGuo/Telepathy/blob/dev-integration/deploy/azuredeploy.json'
          overrideParameters: '-userAssignedIdentity "/subscriptions/a486e243-747b-42de-8c4c-379f8295a746/resourceGroups/haiguoteleid/providers/Microsoft.ManagedIdentity/userAssignedIdentities/haiguotelepathyid" -SSHPublicKey $(SshPublicKey) -servicePrincipalClientId "f510c0e6-16ea-48d3-9c5f-b1a3ecde4055" -servicePrincipalClientSecret $(aksSpSecret)'
          deploymentMode: 'Incremental'
          
  - job: DeployContainer
    displayName: Deploy to AKS
    dependsOn: ARMDeployment
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Subscription-1(a486e243-747b-42de-8c4c-379f8295a746)'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az aks get-credentials --resource-group $(resourceGroup) --name $(aksClusterName)
            kubectl apply -f $(Build.SourcesDirectory)/deploy/manifests/
          addSpnToEnvironment: true



